language: php

php:
  - '5.6'
  - '7.1'
  - '7.2'
  - '7.3'

notifications:
  email: false

before_script:
  - composer self-update
  - composer update --prefer-source

script:
  - composer test
